binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    balancing:
      name: "${name} bms0 balancing"
    charging:
      name: "${name} bms0 charging"
    discharging:
      name: "${name} bms0 discharging"
    online_status:
      name: "${name} bms0 online status"
      
sensor:

  - platform: jbd_bms
    jbd_bms_id: bms0
    battery_strings:
      name: "${name} bms0 battery strings"
    current:
      name: "${name} bms0 current"
    power:
      name: "${name} bms0 power"
      id: jbd_bms_bms0_power
    charging_power:
      name: "${name} bms0 charging power"
    discharging_power:
      name: "${name} bms0 discharging power"
    state_of_charge:
      name: "${name} bms0 state of charge"
    nominal_capacity:
      name: "${name} bms0 nominal capacity"
    charging_cycles:
      name: "${name} bms0 charging cycles"
    capacity_remaining:
      name: "${name} bms0 capacity remaining"
    battery_cycle_capacity:
      name: "${name} bms0 battery cycle capacity"
    total_voltage:
      name: "${name} bms0 total voltage"
    average_cell_voltage:
      name: "${name} bms0 average cell voltage"
    delta_cell_voltage:
      name: "${name} bms0 delta cell voltage"
    min_cell_voltage:
      name: "${name} bms0 min cell voltage"
    max_cell_voltage:
      name: "${name} bms0 max cell voltage"
    min_voltage_cell:
      name: "${name} bms0 min voltage cell"
    max_voltage_cell:
      name: "${name} bms0 max voltage cell"
    temperature_1:
      name: "${name} bms0 temperature 1"
    temperature_2:
      name: "${name} bms0 temperature 2"
    temperature_3:
      name: "${name} bms0 temperature 3"
    temperature_4:
      name: "${name} bms0 temperature 4"
    temperature_ambient:
      name: "${name} bms0 temperature ambient"
    temperature_fet:
      name: "${name} bms0 temperature fet"
    cell_voltage_1:
      name: "${name} bms0 cell voltage 1"
    cell_voltage_2:
      name: "${name} bms0 cell voltage 2"
    cell_voltage_3:
      name: "${name} bms0 cell voltage 3"
    cell_voltage_4:
      name: "${name} bms0 cell voltage 4"
    cell_voltage_5:
      name: "${name} bms0 cell voltage 5"
    cell_voltage_6:
      name: "${name} bms0 cell voltage 6"
    cell_voltage_7:
      name: "${name} bms0 cell voltage 7"
    cell_voltage_8:
      name: "${name} bms0 cell voltage 8"
    cell_voltage_9:
      name: "${name} bms0 cell voltage 9"
    cell_voltage_10:
      name: "${name} bms0 cell voltage 10"
    cell_voltage_11:
      name: "${name} bms0 cell voltage 11"
    cell_voltage_12:
      name: "${name} bms0 cell voltage 12"
    cell_voltage_13:
      name: "${name} bms0 cell voltage 13"
    cell_voltage_14:
      name: "${name} bms0 cell voltage 14"
    cell_voltage_15:
      name: "${name} bms0 cell voltage 15"
    cell_voltage_16:
      name: "${name} bms0 cell voltage 16"
    operation_status_bitmask:
      name: "${name} bms0 operation status bitmask"
    errors_bitmask:
      name: "${name} bms0 errors bitmask"
    alarm_bitmask:
        name: "${name} bms0 alarm bitmask"
    balancer_status_bitmask:
      name: "${name} bms0 balancer status bitmask"
    software_version:
      name: "${name} bms0 software version"
  
  - platform: template
    name:  "${name} bms0 positive power"
    unit_of_measurement: "W"
    lambda: |-
      if (id(jbd_bms_bms0_power).state > 0) {
        return id(jbd_bms_bms0_power).state;
      } else {
        return -id(jbd_bms_bms0_power).state;
      }
    update_interval: 2s

text_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    errors:
      name: "${name} bms0 errors"
    alarms:
      name: "${name} bms0 alarms"
    operation_status:
      name: "${name} bms0 operation status"
    device_model:
      name: "${name} bms0 device model"
 
switch:
  - platform: gpio
    pin:
     number: GPIO19
     inverted: true
    name: "Bms0 enable external balancer"
    id: bms0_external_balancer_switch

  - platform: jbd_bms
    jbd_bms_id: bms0
    charging:
      name: "${name} bms0 charging"
    discharging:
      name: "${name} bms0 discharging"
    balancer:
      name: "${name} bms0 balancer"
