substitutions:
  name: l3inv
  pip_loop_interval: 0ms
  pip_update_interval: 1ms
  jbd_update_inverval: 2000ms

esphome:
  name: ${name}
  friendly_name: L3 Inverter
  comment: "EASun iGrid-IV-5.6kw L3 Inverter and JBD-UP16S010-BMS RS232 monitoring."

esp32:
  board: nodemcu-32s
  # framework:
  #   type: esp-idf

external_components:
  - source:
      type: local
      path: components
  # - source:
  #     type: git
  #     url: https://github.com/maquowicz/esphome-pipsolar.git
  #     ref: pi18
    components: [pipsolar, jbd_bms]
  # refresh: 300000s

# Enable logging
logger:
  level: DEBUG
  #level: INFO
  baud_rate: 0 # disable UART logs
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  # fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: 192.168.0.197 # override for ota if hostname changes

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

# time:
#   - platform: homeassistant
#     id: hass_time

uart:

  - id: uart_ch1
    rx_pin: GPIO16 # ST232 R1.out (12) > GPIO16
    tx_pin: GPIO17 # ST232 T1.in (11) > GPIO17
    baud_rate: 2400

  - id: uart_ch2
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
    # debug: # this wipes out uart read buffer 
    #  direction: BOTH
    #  #dummy_receiver: true
    #  after:
    #    delimiter: "\r"
    #  sequence:
    #    - lambda: UARTDebug::log_string(direction, bytes);

jbd_bms:
  - id: bms0
    uart_id: uart_ch2
    update_interval: ${jbd_update_inverval}
    rx_timeout: 500ms
    modbus_id: 0

pipsolar:
  - uart_id: uart_ch1
    id: inverter0
    update_interval: ${pip_update_interval}

<<: !include l3inv/merged.yaml
