binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    balancing:
      name: "bms balancing"
    charging:
      name: "bms charging"
    discharging:
      name: "bms discharging"
    online_status:
      name: "bms online status"
      
sensor:

  - platform: jbd_bms
    jbd_bms_id: bms0
    battery_strings:
      name: "bms battery strings"
    current:
      name: "bms current"
    power:
      name: "bms power"
      id: jbd_bms_bms0_power
    charging_power:
      name: "bms charging power"
    discharging_power:
      name: "bms discharging power"
    state_of_charge:
      name: "bms state of charge"
    nominal_capacity:
      name: "bms nominal capacity"
    charging_cycles:
      name: "bms charging cycles"
    capacity_remaining:
      name: "bms capacity remaining"
    battery_cycle_capacity:
      name: "bms battery cycle capacity"
    total_voltage:
      name: "bms total voltage"
    average_cell_voltage:
      name: "bms average cell voltage"
    delta_cell_voltage:
      name: "bms delta cell voltage"
    min_cell_voltage:
      name: "bms min cell voltage"
    max_cell_voltage:
      name: "bms max cell voltage"
    min_voltage_cell:
      name: "bms min voltage cell"
    max_voltage_cell:
      name: "bms max voltage cell"
    temperature_1:
      name: "bms temperature 1"
    temperature_2:
      name: "bms temperature 2"
    temperature_3:
      name: "bms temperature 3"
    temperature_4:
      name: "bms temperature 4"
    temperature_ambient:
      name: "bms temperature ambient"
    temperature_fet:
      name: "bms temperature fet"
    cell_voltage_1:
      name: "bms cell voltage 1"
    cell_voltage_2:
      name: "bms cell voltage 2"
    cell_voltage_3:
      name: "bms cell voltage 3"
    cell_voltage_4:
      name: "bms cell voltage 4"
    cell_voltage_5:
      name: "bms cell voltage 5"
    cell_voltage_6:
      name: "bms cell voltage 6"
    cell_voltage_7:
      name: "bms cell voltage 7"
    cell_voltage_8:
      name: "bms cell voltage 8"
    cell_voltage_9:
      name: "bms cell voltage 9"
    cell_voltage_10:
      name: "bms cell voltage 10"
    cell_voltage_11:
      name: "bms cell voltage 11"
    cell_voltage_12:
      name: "bms cell voltage 12"
    cell_voltage_13:
      name: "bms cell voltage 13"
    cell_voltage_14:
      name: "bms cell voltage 14"
    cell_voltage_15:
      name: "bms cell voltage 15"
    cell_voltage_16:
      name: "bms cell voltage 16"
    operation_status_bitmask:
      name: "bms operation status bitmask"
    errors_bitmask:
      name: "bms errors bitmask"
    alarm_bitmask:
        name: "bms alarm bitmask"
    balancer_status_bitmask:
      name: "bms balancer status bitmask"
    software_version:
      name: "bms software version"
  
  - platform: template
    name:  "bms positive power"
    unit_of_measurement: "W"
    lambda: |-
      if (id(jbd_bms_bms0_power).state > 0) {
        return id(jbd_bms_bms0_power).state;
      } else {
        return -id(jbd_bms_bms0_power).state;
      }
    update_interval: ${jbd_update_inverval}

text_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms0
    errors:
      name: "bms errors"
    alarms:
      name: "bms alarms"
    operation_status:
      name: "bms operation status"
    device_model:
      name: "bms device model"
 
switch:
  - platform: gpio
    pin:
     number: GPIO19
     inverted: true
    name: "bms enable external balancer"
    id: bms0_external_balancer_switch

  - platform: jbd_bms
    jbd_bms_id: bms0
    charging:
      name: "bms charging"
    discharging:
      name: "bms discharging"
    balancer:
      name: "bms balancer"
